### ISSUE TITLE
Mines & Tower predictor server seed(hashed) stake?

### ISSUE THREAD

**Issue by Sebfrcan** [Geekeh/Bloxflip-Mines-Predictor-Discord-Bot#11]
Hi @Geekeh and @michx1337 i want to know how to edit the 
Round ID  to make it compatible with stake.com(server seed(hashed) : 4616ba7cd3b6b89b92a1f06bcff95a9bae13a0ac36d6703c360cad349b0ae2d8

Let me know thanks for the mines and for tower what i need to edit thanks 🙂

I know your predictor is random and its genius !!
And is it possible to make the predictor work 24h 7days/7 on my discord server ? 

Waiting for a reply from u guys thanks a lot for what u did !!

**Comment by Zard-Studios** [comment]
read the fucking main.py code, this is a randomizer not a predictor stay safe!

**Comment by st4rted** [comment]
> read the fucking main.py code, this is a randomizer not a predictor stay safe!

Read the post again, you idiot. He clearly said he knows this is random. 🙀
