### ISSUE TITLE
bro it just creates random mines, plus the accuracy is random too, it only checks the length of the round id bruh that's it

### ISSUE THREAD

**Issue by sponege** [Geekeh/Bloxflip-Mines-Predictor-Discord-Bot#22]
did you make this to sell this scam to people bruh

**Comment by Daltans04** [comment]
Can you shot down my applications

**Comment by sponege** [comment]
@Daltans04 what do you mean

**Comment by Scaroontop** [comment]
> did you make this to sell this scam to people bruh

Then why would he release it then

**Comment by Unused1account5838383** [comment]
no fuckin shit

**Comment by MartinUQ** [comment]
This who made this is retarded
